# Generated by Django 3.0.3 on 2020-04-08 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.TextField()),
                ('attachments', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
                ('due', models.DateField()),
                ('petition_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='petitionfor', to=settings.AUTH_USER_MODEL)),
                ('petitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitioner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
