# Generated by Django 3.0.3 on 2020-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
